name: Build
on:
  push:

# Queue jobs to ensure that only newer code is deployed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel older jobs if we're not on main
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    name: Build Docker image (${{ matrix.test-case }})
    runs-on:
      labels: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-case:
        - conda
        - conda-lock
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: |
          make build
        env:
          EXAMPLE_DOCKERFILES: ${{ matrix.test-case }}.Dockerfile
          ANACONDA_AUTH_API_KEY: ${{ secrets.ANACONDA_AUTH_API_KEY }}
