# Run a special docker build to test the authentication behavior via our test plugin mechanism
name: Test
on:
  push:

# Queue jobs to ensure that only newer code is deployed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Cancel older jobs if we're not on main
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Test registered build (${{ matrix.test-case }})
    runs-on:
      labels: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-case:
        - conda
        - conda-lock
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run test build
        run: |
          make test
        env:
          TEST_DOCKERFILES: ${{ matrix.test-case }}.Dockerfile
          ANACONDA_AUTH_API_KEY: ${{ secrets.ANACONDA_AUTH_API_KEY }}

  test-dotenv:
    name: Test registered build (.env)
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Generate docker.env file
        run: |
          echo "ANACONDA_AUTH_API_KEY=${{ env.ANACONDA_AUTH_API_KEY }}" > ./docker.env
        env:
          ANACONDA_AUTH_API_KEY: ${{ secrets.ANACONDA_AUTH_API_KEY }}
      - name: Run test build
        run: |
          make test-dotenv
